# Generated by Django 2.2.6 on 2019-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(max_length=15),
        ),
    ]
